const GlOBALTYPE = {
  GETCARS: "GETCARS",
  GET_CARS_SUCCESS: "GET_CARS_SUCCESS",
  GET_CARS_FAIL: "GET_CARS_FAIL",
  GET_FOOD: "GET_FOOD",
  GET_FOOD_SUCCESS: "GET_FOOD_SUCCESS",
  GET_FOOD_FAIL: "GET_FOOD_FAIL"
};

export default GlOBALTYPE;
