const GlOBALTYPE = {
  GETCARS: "GETCARS",
  GET_CARS_SUCCESS: "GET_CARS_SUCCESS",
  GET_CARS_FAIL: "GET_CARS_FAIL",
  GET_FOOD: "GET_FOOD",
  GET_FOOD_SUCCESS: "GET_FOOD_SUCCESS",
  GET_FOOD_FAIL: "GET_FOOD_FAIL",
  EDIT_CAR: "EDIT_CAR",
  EDIT_FOOD: "EDIT_FOOD",
  DELETE_FOOD: "DELETE_FOOD",
  DELETE_CAR: "DELETE_CAR",
};

export default GlOBALTYPE;
